// app/api/admin/download-zip/route.ts
// Generates a ZIP with position-based folders:
// President/ | Vice President/ | General Secretary/ | Treasurer/
// Each folder: {name}.pdf + {name}_details.txt

import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { cvSubmissions, users } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import JSZip from "jszip";
import { get } from "@vercel/blob";

const ADMIN_EMAILS = (process.env.ADMIN_EMAILS ?? "")
  .split(",")
  .map((e) => e.trim().toLowerCase())
  .filter(Boolean);

function toFolderName(position: string): string {
  return position.replace(/\s+/g, "_");
}

function buildDetailsText(row: {
  fullName: string;
  studentId: string;
  phone: string;
  position: string;
  semester: number;
  department: string;
  cgpa: string;
  experienceDetails: string;
  whyAppropriate: string;
  deviceInfo: string;
  userEmail: string;
  filename: string;
  uploadedAt: Date;
}): string {
  let deviceFormatted = "";
  try {
    if (row.deviceInfo) {
      const dev = JSON.parse(row.deviceInfo);
      deviceFormatted = [
        `Device OS/Platform: ${dev.platform || "Unknown"}`,
        `Screen Resolution: ${dev.screen || "Unknown"}`,
        `Timezone          : ${dev.timezone || "Unknown"}`,
        `Browser Locale    : ${dev.language || "Unknown"}`,
        `User Agent        : ${dev.userAgent || "Unknown"}`,
        `Browser Cookie ID : ${dev.deviceId || "N/A"}`
      ].join("\n");
    }
  } catch (e) {
    deviceFormatted = "Invalid JSON or raw: " + row.deviceInfo;
  }

  return [
    "=== Primeasia University Sports Club ===",
    "Executive Committee Application Details",
    "========================================",
    "",
    `Full Name    : ${row.fullName}`,
    `Email        : ${row.userEmail}`,
    `Student ID   : ${row.studentId}`,
    `Phone        : ${row.phone}`,
    `Position     : ${row.position}`,
    `Semester     : ${row.semester}`,
    `Department   : ${row.department}`,
    `CGPA         : ${row.cgpa}`,
    `CV Filename  : ${row.filename}`,
    `Submitted At : ${row.uploadedAt.toLocaleString("en-GB", { timeZone: "Asia/Dhaka" })}`,
    "",
    "=== Club & Leadership Experience ===",
    row.experienceDetails || "None provided.",
    "",
    "=== Why Appropriate for Post ===",
    row.whyAppropriate || "None provided.",
    "",
    "=== Security Auditing Device Telemetry ===",
    deviceFormatted || "None collected.",
    "",
    "========================================",
    "Generated by Primeasia University Sports Club Admin System",
  ].join("\n");
}

export async function GET() {
  const session = await auth();
  const email = session?.user?.email?.toLowerCase();

  if (!email || !ADMIN_EMAILS.includes(email)) {
    return new NextResponse("Unauthorized", { status: 401 });
  }

  // Fetch all submissions with user email and new fields
  const rows = await db
    .select({
      id: cvSubmissions.id,
      fullName: cvSubmissions.fullName,
      studentId: cvSubmissions.studentId,
      phone: cvSubmissions.phone,
      position: cvSubmissions.position,
      semester: cvSubmissions.semester,
      department: cvSubmissions.department,
      cgpa: cvSubmissions.cgpa,
      experienceDetails: cvSubmissions.experienceDetails,
      whyAppropriate: cvSubmissions.whyAppropriate,
      deviceInfo: cvSubmissions.deviceInfo,
      blobUrl: cvSubmissions.blobUrl,
      filename: cvSubmissions.filename,
      uploadedAt: cvSubmissions.uploadedAt,
      userEmail: users.email,
    })
    .from(cvSubmissions)
    .innerJoin(users, eq(cvSubmissions.userId, users.id));

  if (rows.length === 0) {
    return new NextResponse("No submissions found", { status: 404 });
  }

  const zip = new JSZip();

  await Promise.all(
    rows.map(async (row) => {
      const positionFolderName = toFolderName(row.position);
      const positionFolder = zip.folder(positionFolderName)!;

      // Sanitize student name for folder name
      const safeName = row.fullName
        .replace(/[^a-zA-Z0-9\s_-]/g, "")
        .trim()
        .replace(/\s+/g, "_");

      // Create student subfolder under the position folder
      const studentFolder = positionFolder.folder(safeName)!;

      // Fetch CV PDF from Vercel Blob
      try {
        const result = await get(row.blobUrl, {
          access: "private",
          token: process.env.BLOB_READ_WRITE_TOKEN,
        });
        if (result) {
          const { stream } = result;
          const pdfBuffer = await new Response(stream).arrayBuffer();
          studentFolder.file(`${safeName}.pdf`, pdfBuffer);
        }
      } catch (err) {
        console.error("ZIP download fetch error for:", row.fullName, err);
        // Skip if fetch fails; still include txt
      }

      // Add details text file inside the student folder
      const detailsTxt = buildDetailsText(row);
      studentFolder.file(`${safeName}_details.txt`, detailsTxt);
    })
  );

  const zipBuffer = await zip.generateAsync({
    type: "uint8array",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return new NextResponse(new Blob([Buffer.from(zipBuffer)], { type: "application/zip" }), {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="PaUSC_All_Applicants_${Date.now()}.zip"`,
    },
  });
}
